name: 'Auto-update Asana status fields'
description: 'This action updates a specific custom field in Asana that we have at Spruce depending on Pull Request status'
author: 'Jonathan Sibley'
inputs:
  mainBranchName:
    required: false
    description: 'the name of the repo main branch'
    default: 'main'
  asanaToken:
    required: true
    description: 'an Asana token with access to the projects and tasks you want to update'
    default: ''
  githubToken:
    required: true
    description: 'GitHub token for authentication and API access'
    default: ''
  pull-request-description:
    description: 'Pull request description (optional override). Otherwise it will be retrieved from the workflow context.'
    required: false
  statusFieldName:
    required: false
    description: 'if specified, this custom field will be set automatically when a PR is opened or merged'
    default: ''
  statusFieldValueWhenDraftPRIsOpen:
    required: false
    description: 'if specified, the statusFieldName will be set to the enum of this value when a PR is in draft mode. This should be the name of the enum value, as it appears in the Asana UI (as opposed to the GID or some other identifier).'
    default: ''
  statusFieldValueWhenPRReadyForReviewIsOpen:
    required: false
    description: 'if specified, the statusFieldName will be set to the enum of this value when a PR is ready for review (not in draft mode). This should be the name of the enum value, as it appears in the Asana UI (as opposed to the GID or some other identifier).'
    default: ''
  statusFieldValueForMergedCommitToMain:
    required: false
    description: 'if specified, the statusFieldName will be set to the enum of this value when a PR is merged into main (or any other commit is pushed to main, for that matter). This should be the name of the enum value, as it appears in the Asana UI (as opposed to the GID or some other identifier).'
    default: ''
  dontUpdateStatusFieldWhenReviewIsApprovedIfStatusFieldValueIsCurrentlyOneOf:
    required: false
    description: 'A comma-separated list of status field values. If the status field is currently set to one of these values, the status field will not be updated when a PR is approved.'
    default: ''
  statusFieldValueWhenPRReadyForReviewIsApproved:
    required: false
    description: 'if specified, the statusFieldName will be set to the enum of this value when a PR is approved and ready for review. This should be the name of the enum value, as it appears in the Asana UI (as opposed to the GID or some other identifier).'
    default: ''
  skipSettingStatusForPRReadyForReviewIsApprovedIfLabeledWith:
    required: false
    description: 'A comma-separated list of labels. If the PR has any of these labels, the status will not be set to the "approved" value even if the PR is approved.'
    default: ''
  labelToApplyToPRWhenApproved:
    required: false
    description: 'If specified, the PR will be labeled with this value when the status is updated to the value of `statusFieldValueWhenPRReadyForReviewIsApproved`.'
    default: ''
outputs:
  didSetStatus:
    description: 'true if the status was set, false or undefined if not set'
  statusFieldValue:
    description: 'the value of the status field that was set, or undefined if not set'
runs:
  using: 'node20'
  main: 'dist/index.js'
